### ISSUE TITLE
[Bug]: dingdingBot 返回ok，机器人却收不到消息问题

### ISSUE THREAD

**Issue by duliang123** [veops/ops-tools#20]
### This bug is related to UI or API?

API

### What happened?

接收方：钉钉群机器人
机器人设置：自定义关键词+加签
操作：
`# bash test.sh 
{"msg":"ok"} `
测试条件：content 消息体没加机器人自定义关键词
问题：钉钉群机器人接收不到消息，但是 messenger 返回 ok。

查看log，钉钉已经报错了：
`Nov 25 21:41:52 ali-hz-tunnel messenger[767665]: err=send to dingding bot failed httpcode=200 resp={
Nov 25 21:41:52 ali-hz-tunnel messenger[767665]:  "errcode": 310000,
Nov 25 21:41:52 ali-hz-tunnel messenger[767665]:  "errmsg": "错误描述:关键词不匹配;解决方案:请联系群管理员查看此机器人的关键词，并在发送的信息中包含此关键词;"
Nov 25 21:41:52 ali-hz-tunnel messenger[767665]: }
`

**Comment by ttktatakai** [comment]
Please set sync parameter to true if you want to wait the result of sending. Otherwise, messenger will return ok if the message(which will be sent asynchronously) is received successfully.

**Comment by duliang123** [comment]
Thinks, I think it's better to set sync to true by default.

**Comment by duliang123** [comment]
solved
