### ISSUE TITLE
[Feature]: Bot need supports @members

### ISSUE THREAD

**Issue by duliang123** [veops/ops-tools#21]
### What is your advice?

Bot need supports @members and @all.
It is very useful, I hope developers can develop this feature, thank you.

**Comment by ttktatakai** [comment]
Please check for this PR [https://github.com/veops/ops-tools/pull/22](https://github.com/veops/ops-tools/pull/22)

**Comment by duliang123** [comment]
Messenger已迁移至新的仓库👇

https://github.com/veops/messenger
